Added arch selection

diff --git a/lxc-debian/lxc-template-debian b/lxc-debian/lxc-template-debian
--- a/lxc-debian/lxc-template-debian
+++ b/lxc-debian/lxc-template-debian
@@ -114,7 +114,12 @@ isc-dhcp-client,\
 netbase,\
 net-tools,\
 iproute,\
-openssh-server
+openssh-server,\
+man-db,\
+file,\
+vim,\
+less
+
 
     cache=$1
     arch=$2
@@ -171,8 +176,6 @@ install_debian()
             echo "Cache repository is busy."
             return 1
         fi
-
-        arch=$(dpkg --print-architecture)
 
         echo "Checking cache download in $cache/rootfs-$SUITE-$arch ... "
         if [ ! -e "$cache/rootfs-$SUITE-$arch" ]; then
@@ -267,22 +270,43 @@ clean()
 usage()
 {
     cat <<EOF
-$1 -h|--help -p|--path=<path> --clean
+$1 -h|--help -a|--arch=ARCH -p|--path=<path> --clean
 EOF
     return 0
 }
 
-options=$(getopt -o hp:n:c -l help,path:,name:,clean -- "$@")
+options=$(getopt -o hp:a:n:c -l help,arch:,path:,name:,clean -- "$@")
 if [ $? -ne 0 ]; then
         usage $(basename $0)
         exit 1
 fi
 eval set -- "$options"
 
+arch=$(arch)
+
+# Code taken from debootstrap
+if [ -x /usr/bin/dpkg ] && /usr/bin/dpkg --print-architecture >/dev/null 2>&1; then
+    arch=`/usr/bin/dpkg --print-architecture`
+elif which udpkg >/dev/null 2>&1 && udpkg --print-architecture >/dev/null 2>&1; then
+    arch=`/usr/bin/udpkg --print-architecture`
+else
+    arch=$(arch)
+    if [ "$arch" = "i686" ]; then
+        arch="i386"
+    elif [ "$arch" = "x86_64" ]; then
+        arch="amd64"
+    elif [ "$arch" = "armv7l" ]; then
+        arch="armel"
+    fi
+fi
+
+hostarch=$arch
+
 while true
 do
     case "$1" in
         -h|--help)      usage $0 && exit 0;;
+        -a|--arch)      arch=$2; shift 2;;
         -p|--path)      path=$2; shift 2;;
         -n|--name)      name=$2; shift 2;;
         -c|--clean)     clean=$2; shift 2;;
@@ -290,6 +314,16 @@ do
         *)              break ;;
     esac
 done
+
+
+if [ "$arch" == "i686" ]; then
+    arch=i386
+fi
+
+if [ $hostarch = "i386" -a $arch = "amd64" ]; then
+    echo "can't create amd64 container on i386"
+    exit 1
+fi
 
 if [ ! -z "$clean" -a -z "$path" ]; then
     clean || exit 1
